# Ejercicio 16: DataFrame de estudiantes

**Enunciado:** crear un DataFrame con 10 estudiantes que incluya nombre, carrera, edad, promedio y ciudad.

**Lógica:** se utiliza pandas para crear una tabla de estudiantes. Luego se muestran las primeras filas, la información general, el promedio general, los estudiantes con promedio mayor o igual a 80 y finalmente se ordenan de mayor a menor promedio.

In [5]:
import pandas as pd

datos = {
    "Nombre": ["Ana", "Luis", "Carlos", "María", "José", "Sofía", "Pedro", "Lucía", "Juan", "Gabriela"],
    "Carrera": ["Sistemas", "Derecho", "Medicina", "Sistemas", "Administración", "Psicología", "Civil", "Arquitectura", "Contaduría", "Industrial"],
    "Edad": [20, 21, 22, 19, 23, 20, 24, 22, 21, 20],
    "Promedio": [85, 78, 90, 82, 75, 95, 70, 88, 80, 92],
    "Ciudad": ["Tegucigalpa", "Comayagua", "La Ceiba", "Danlí", "Choluteca", "SPS", "Juticalpa", "Siguatepeque", "Tela", "Tegucigalpa"]
}

df = pd.DataFrame(datos)

print("Primeras 5 filas:")
display(df.head())

print("Información general:")
df.info()

promedio_general = df["Promedio"].mean()
print(f"\nPromedio general: {promedio_general:.2f}")

print("\nEstudiantes con promedio mayor o igual a 80:")
display(df[df["Promedio"] >= 80])

print("\nEstudiantes ordenados de mayor a menor promedio:")
display(df.sort_values(by="Promedio", ascending=False))

Primeras 5 filas:

   Nombre         Carrera  Edad  Promedio       Ciudad
0     Ana        Sistemas    20        85  Tegucigalpa
1    Luis         Derecho    21        78    Comayagua
2  Carlos        Medicina    22        90     La Ceiba
3   María        Sistemas    19        82        Danlí
4    José  Administración    23        75    Choluteca

Información general:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    10 non-null     str
 1   Carrera   10 non-null     str
 2   Edad      10 non-null     int64
 3   Promedio  10 non-null     int64
 4   Ciudad    10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

Promedio general: 83.50

Estudiantes con promedio mayor o igual a 80:

     Nombre       Carrera  Edad  Promedio        Ciudad
0       Ana      Sistemas    20        85   Tegucigalpa
2    Carlos      Medicina    22        90      La Ceiba
3     María      Sistemas    19        82         Danlí
5     Sofía    Psicología    20        95           SPS
7     Lucía  Arquitectura    22        88  Siguatepeque
8      Juan    Contaduría    21        80          Tela
9  Gabriela    Industrial    20        92   Tegucigalpa

Estudiantes ordenados de mayor a menor promedio:

     Nombre         Carrera  Edad  Promedio        Ciudad
5     Sofía      Psicología    20        95           SPS
9  Gabriela      Industrial    20        92   Tegucigalpa
2    Carlos        Medicina    22        90      La Ceiba
7     Lucía    Arquitectura    22        88  Siguatepeque
0       Ana        Sistemas    20        85   Tegucigalpa
3     María        Sistemas    19        82         Danlí
8      Juan      Contaduría    21        80          Tela
1      Luis         Derecho    21        78     Comayagua
4      José  Administración    23        75     Choluteca
6     Pedro           Civil    24        70     Juticalpa

## Ejercicio 17: Análisis de ventas con pandas

**Enunciado:** crear un DataFrame de ventas con al menos 15 registros e identificar métricas clave del negocio.

**Lógica:** se construye un DataFrame con las columnas `fecha`, `vendedor`, `producto`, `categoría`, `cantidad` y `precio unitario`. Se calcula la columna `TotalVenta` multiplicando cantidad por precio, luego se agrupan los datos para obtener el total por vendedor, el producto más vendido, la categoría con mayor ingreso y se ordenan las ventas de mayor a menor.

In [6]:
import pandas as pd

datos = {
    "fecha": [
        "2024-03-05","2024-03-12","2024-03-21",
        "2024-04-02","2024-04-18","2024-04-27",
        "2024-05-07","2024-05-14","2024-05-29",
        "2024-06-03","2024-06-19","2024-06-25",
        "2024-07-08","2024-07-17","2024-07-30"
    ],
    "vendedor": [
        "Ana","Ana","Ana",
        "Luis","Luis","Luis",
        "Carlos","Carlos","Carlos",
        "María","María","María",
        "Jorge","Jorge","Jorge"
    ],
    "producto": [
        "Laptop","Audífonos Bluetooth","Silla Ergonómica",
        "Monitor 27 pulgadas","Teclado Mecánico","Webcam HD",
        "Smartphone","Tablet","Cargador Inalámbrico",
        "Impresora","Mouse Inalámbrico","Escritorio",
        "Laptop Gamer","Micrófono USB","Lámpara LED"
    ],
    "categoria": [
        "Electrónica","Audio","Mobiliario",
        "Electrónica","Accesorios","Accesorios",
        "Telefonía","Telefonía","Accesorios",
        "Oficina","Accesorios","Mobiliario",
        "Electrónica","Audio","Iluminación"
    ],
    "cantidad": [2, 3, 1, 2, 4, 5, 3, 2, 6, 1, 7, 1, 2, 4, 5],
    "precio_unitario": [
        1500, 80, 350,
        300, 95, 75,
        850, 450, 35,
        220, 30, 480,
        2200, 120, 40
    ]
}

df = pd.DataFrame(datos)

df["TotalVenta"] = df["cantidad"] * df["precio_unitario"]

print("DataFrame completo")
print(df)

print("\nTotal vendido por vendedor")
print(df.groupby("vendedor")["TotalVenta"].sum())

print("\nProducto más vendido")
print(df.groupby("producto")["cantidad"].sum().idxmax())

print("\nCategoría con mayor ingreso")
print(df.groupby("categoria")["TotalVenta"].sum().idxmax())

print("\nVentas ordenadas de mayor a menor")
print(df[["producto", "precio_unitario", "TotalVenta"]].sort_values("TotalVenta", ascending=False))

DataFrame completo
         fecha vendedor              producto    categoria  cantidad  \
0   2024-03-05      Ana                Laptop  Electrónica         2
1   2024-03-12      Ana   Audífonos Bluetooth        Audio         3
2   2024-03-21      Ana      Silla Ergonómica   Mobiliario         1
3   2024-04-02     Luis   Monitor 27 pulgadas  Electrónica         2
4   2024-04-18     Luis      Teclado Mecánico   Accesorios         4
5   2024-04-27     Luis             Webcam HD   Accesorios         5
6   2024-05-07   Carlos            Smartphone    Telefonía         3
7   2024-05-14   Carlos                Tablet    Telefonía         2
8   2024-05-29   Carlos  Cargador Inalámbrico   Accesorios         6
9   2024-06-03    María             Impresora      Oficina         1
10  2024-06-19    María     Mouse Inalámbrico   Accesorios         7
11  2024-06-25    María            Escritorio   Mobiliario         1
12  2024-07-08    Jorge          Laptop Gamer  Electrónica         2
13  2024-07-17    Jorge         Micrófono USB        Audio         4
14  2024-07-30    Jorge           Lámpara LED  Iluminación         5

    precio_unitario  TotalVenta
0              1500        3000
1                80         240
2               350         350
3               300         600
4                95         380
5                75         375
6               850        2550
7               450         900
8                35         210
9               220         220
10               30         210
11              480         480
12             2200        4400
13              120         480
14               40         200

Total vendido por vendedor
vendedor
Ana       3590
Carlos    3660
Jorge     5080
Luis      1355
María      910
Name: TotalVenta, dtype: int64

Producto más vendido
Mouse Inalámbrico

Categoría con mayor ingreso
Electrónica

Ventas ordenadas de mayor a menor
                producto  precio_unitario  TotalVenta
12          Laptop Gamer             2200        4400
0                 Laptop             1500        3000
6             Smartphone              850        2550
7                 Tablet              450         900
3    Monitor 27 pulgadas              300         600
13         Micrófono USB              120         480
11            Escritorio              480         480
4       Teclado Mecánico               95         380
5              Webcam HD               75         375
2       Silla Ergonómica              350         350
1    Audífonos Bluetooth               80         240
9              Impresora              220         220
8   Cargador Inalámbrico               35         210
10     Mouse Inalámbrico               30         210
14           Lámpara LED               40         200

## Ejercicio 18: Limpieza de datos con pandas

**Enunciado:** realizar un proceso básico de limpieza de datos utilizando pandas.

**Lógica:** se crea un DataFrame de clientes, se cuentan los valores nulos, se rellenan las ciudades vacías con un valor por defecto y se eliminan las filas que no tengan correo registrado.

In [7]:
import pandas as pd
import numpy as np


datos = {
    "nombre": ["johnny", "Katherine", "Carlos", "María", "Marco"],
    
    "edad": [25, 30, np.nan, 28, 35],
    
    "correo": [
        "johnny@gmail.com",
        None,
        "carlos@gmail.com",
        "maria@gmail.com",
        None
    ],
    
    "ciudad": [
        "Tegucigalpa",
        "",
        "San Pedro Sula",
        "",
        "La Ceiba"
    ],
    
    "telefono": [
        "9999-1111",
        "8888-2222",
        None,
        "7777-3333",
        "6666-4444"
    ]
}

df = pd.DataFrame(datos)


print("DataFrame original:")
print(df)


print("\nValores nulos:")
print(df.isnull())


print("\nCantidad de valores nulos por columna:")
print(df.isnull().sum())


df["ciudad"] = df["ciudad"].replace("", "No especificada")


df_limpio = df.dropna(subset=["correo"])


print("\nDataFrame limpio:")
print(df_limpio)

DataFrame original:
      nombre  edad            correo          ciudad   telefono
0     johnny  25.0  johnny@gmail.com     Tegucigalpa  9999-1111
1  Katherine  30.0               NaN                  8888-2222
2     Carlos   NaN  carlos@gmail.com  San Pedro Sula        NaN
3      María  28.0   maria@gmail.com                  7777-3333
4      Marco  35.0               NaN        La Ceiba  6666-4444

Valores nulos:
   nombre   edad  correo  ciudad  telefono
0   False  False   False   False     False
1   False  False    True   False     False
2   False   True   False   False      True
3   False  False   False   False     False
4   False  False    True   False     False

Cantidad de valores nulos por columna:
nombre      0
edad        1
correo      2
ciudad      0
telefono    1
dtype: int64

DataFrame limpio:
   nombre  edad            correo           ciudad   telefono
0  johnny  25.0  johnny@gmail.com      Tegucigalpa  9999-1111
2  Carlos   NaN  carlos@gmail.com   San Pedro Sula        NaN
3   María  28.0   maria@gmail.com  No especificada  7777-3333

## Ejercicio 19: Análisis de préstamos

**Enunciado:** analizar varias solicitudes de préstamo para conocer su estado, los montos solicitados y características generales de los clientes.

**Lógica:** se crea un DataFrame con las solicitudes de préstamo, se exploran los datos para identificar montos, estados y características clave de cada cliente.

Se utilizaron varios metodos de pandas para trabajar con los datos. **DataFrame()** permitio crear y organizar la tabla con la informacion de prestamos. **mean()** se uso para obtener el promedio de los montos solicitados. **value_counts** ayudo a contar cuantas solicitudes habia en cada estado. **groupby()** permitio agrupar los datos segun el estado de la solicitud, y junto con **mean()** sirivio para calcular el promedio del monto solicitado en cada grupo. Ademas, los filtros facilitaron mostrar solo ciertos registros, como los prestamos aprobados o los montos mayores a 50,000.

In [8]:
import pandas as pd

data = {
    "cliente": ["Jorge", "Luis", "Carlos", "Maria", "Sofia", "Pedro"],
    "monto_sol": [45000, 60000, 30000, 80000, 52000, 40000],
    "plazo": [12, 24, 6, 36, 18, 12],
    "ingreso_men": [15000, 22000, 12000, 30000, 25000, 18000],
    "estado": ["Aprobado", "Pendiente", "Rechazado", "Aprobado", "Aprobado", "Pendiente"]
}

df = pd.DataFrame(data)

print("DataFrame de solicitudes de prestamo:")
print(df)

prom_monto = df["monto_sol"].mean()
print("\nMonto promedio solicitado:", prom_monto)

conteo_estados = df["estado"].value_counts()
print("\nCantidad de solicitudes por estado:")
print(conteo_estados)

aprobados = df[df["estado"] == "Aprobado"]
print("\nPrestamos aprobados:")
print(aprobados)

mayores = df[df["monto_sol"] > 50000]
print("\nClientes con monto solicitado mayor a 50,000:")
print(mayores)

promedio_est = df.groupby("estado")["monto_sol"].mean()
print("\nPromedio del monto solicitado por estado:")
print(promedio_est)

DataFrame de solicitudes de prestamo:
  cliente  monto_sol  plazo  ingreso_men     estado
0   Jorge      45000     12        15000   Aprobado
1    Luis      60000     24        22000  Pendiente
2  Carlos      30000      6        12000  Rechazado
3   Maria      80000     36        30000   Aprobado
4   Sofia      52000     18        25000   Aprobado
5   Pedro      40000     12        18000  Pendiente

Monto promedio solicitado: 51166.666666666664

Cantidad de solicitudes por estado:
estado
Aprobado     3
Pendiente    2
Rechazado    1
Name: count, dtype: int64

Prestamos aprobados:
  cliente  monto_sol  plazo  ingreso_men    estado
0   Jorge      45000     12        15000  Aprobado
3   Maria      80000     36        30000  Aprobado
4   Sofia      52000     18        25000  Aprobado

Clientes con monto solicitado mayor a 50,000:
  cliente  monto_sol  plazo  ingreso_men     estado
1    Luis      60000     24        22000  Pendiente
3   Maria      80000     36        30000   Aprobado
4   Sofia      52000     18        25000   Aprobado

Promedio del monto solicitado por estado:
estado
Aprobado     59000.0
Pendiente    50000.0
Rechazado    30000.0
Name: monto_sol, dtype: float64

## Ejercicio 20: Mini análisis de datos tipo empresa

Se utilizaron varios metodos de pandas para trabajar con los datos de los empleados. DataFrame() permitio crear y organizar la informacion en forma de tabla. head() se uso para mostrar los primeros registros del DataFrame. describe() ayudo a obtener estadisticas generales de los salarios, como promedio, minimo y maximo. groupby() junto con mean() permitio calcular el salario promedio por departamento.

In [9]:
import pandas as pd

data = {
    "nombre": ["Ana", "Carlos", "Maria", "Luis", "Sofia", "Pedro"],
    "departamento": ["IT", "Ventas", "RRHH", "IT", "Marketing", "Ventas"],
    "cargo": ["Programador", "Vendedor", "Reclutadora", "Analista", "Diseñadora", "Supervisor"],
    "salario": [25000, 18000, 22000, 30000, 21000, 27000],
    "años_exp": [2, 6, 4, 8, 3, 10],
    "ciudad": ["Tegucigalpa", "San Pedro", "La Ceiba", "Tegucigalpa", "Choluteca", "San Pedro"]
}

df = pd.DataFrame(data)

print("DataFrame de empleados:")
print(df)

print("\nPrimeros registros:")
print(df.head())

estadisticas = df["salario"].describe()
print("\nEstadisticas generales de salarios:")
print(estadisticas)

promedio_dep = df.groupby("departamento")["salario"].mean()
print("\nSalario promedio por departamento:")
print(promedio_dep)

mayor_salario = df[df["salario"] == df["salario"].max()]
print("\nEmpleado con salario mas alto:")
print(mayor_salario)

mayor_exp = df[df["años_exp"] > 5]
print("\nEmpleados con mas de 5 años de experiencia:")
print(mayor_exp)

ordenados = df.sort_values(by="salario", ascending=False)
print("\nEmpleados ordenados por salario:")
print(ordenados)

def nivel_experiencia(años):
    if años <= 2:
        return "Junior"
    elif años <= 5:
        return "Intermedio"
    else:
        return "Senior"

df["NivelExperiencia"] = df["años_exp"].apply(nivel_experiencia)

print("\nDataFrame con nivel de experiencia:")
print(df)

DataFrame de empleados:
   nombre departamento        cargo  salario  años_exp       ciudad
0     Ana           IT  Programador    25000         2  Tegucigalpa
1  Carlos       Ventas     Vendedor    18000         6    San Pedro
2   Maria         RRHH  Reclutadora    22000         4     La Ceiba
3    Luis           IT     Analista    30000         8  Tegucigalpa
4   Sofia    Marketing   Diseñadora    21000         3    Choluteca
5   Pedro       Ventas   Supervisor    27000        10    San Pedro

Primeros registros:
   nombre departamento        cargo  salario  años_exp       ciudad
0     Ana           IT  Programador    25000         2  Tegucigalpa
1  Carlos       Ventas     Vendedor    18000         6    San Pedro
2   Maria         RRHH  Reclutadora    22000         4     La Ceiba
3    Luis           IT     Analista    30000         8  Tegucigalpa
4   Sofia    Marketing   Diseñadora    21000         3    Choluteca

Estadisticas generales de salarios:
count        6.000000
mean     23833.333333
std       4355.073669
min      18000.000000
25%      21250.000000
50%      23500.000000
75%      26500.000000
max      30000.000000
Name: salario, dtype: float64

Salario promedio por departamento:
departamento
IT           27500.0
Marketing    21000.0
RRHH         22000.0
Ventas       22500.0
Name: salario, dtype: float64

Empleado con salario mas alto:
  nombre departamento     cargo  salario  años_exp       ciudad
3   Luis           IT  Analista    30000         8  Tegucigalpa

Empleados con mas de 5 años de experiencia:
   nombre departamento       cargo  salario  años_exp       ciudad
1  Carlos       Ventas    Vendedor    18000         6    San Pedro
3    Luis           IT    Analista    30000         8  Tegucigalpa
5   Pedro       Ventas  Supervisor    27000        10    San Pedro

Empleados ordenados por salario:
   nombre departamento        cargo  salario  años_exp       ciudad
3    Luis           IT     Analista    30000         8  Tegucigalpa
5   Pedro       Ventas   Supervisor    27000        10    San Pedro
0     Ana           IT  Programador    25000         2  Tegucigalpa
2   Maria         RRHH  Reclutadora    22000         4     La Ceiba
4   Sofia    Marketing   Diseñadora    21000         3    Choluteca
1  Carlos       Ventas     Vendedor    18000         6    San Pedro

DataFrame con nivel de experiencia:
   nombre departamento        cargo  salario  años_exp       ciudad  \
0     Ana           IT  Programador    25000         2  Tegucigalpa
1  Carlos       Ventas     Vendedor    18000         6    San Pedro
2   Maria         RRHH  Reclutadora    22000         4     La Ceiba
3    Luis           IT     Analista    30000         8  Tegucigalpa
4   Sofia    Marketing   Diseñadora    21000         3    Choluteca
5   Pedro       Ventas   Supervisor    27000        10    San Pedro

  NivelExperiencia
0           Junior
1           Senior
2       Intermedio
3           Senior
4       Intermedio
5           Senior